# permissions for end users to edit loremipsums.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: loremipsum-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: loremipsum
    app.kubernetes.io/part-of: loremipsum
    app.kubernetes.io/managed-by: kustomize
  name: loremipsum-editor-role
rules:
- apiGroups:
  - api.broswen.com
  resources:
  - loremipsums
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.broswen.com
  resources:
  - loremipsums/status
  verbs:
  - get
